# main 브랜치에 push 될 때
# 테스트 -> 빌드

name: Run Test and Build
# push 이벤트에 대해서 트리거, 수동으로 트리거
# 배열로 작성하면 여러 이벤트 트리거 사용 가능
on: [push, workflow_dispatch]

jobs:
  # 1. test
  test:
    runs-on: ubuntu-latest
    steps:
      # 코드를 가져옴
      - name: Get Codes
        uses: actions/checkout@v4

      # 의존성 파일 설치
      - name: Install Dependencies
        run: npm install

      # 테스트 실행
      - name: Run Test
        run: npm test

  # 2. build
